name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
     - uses: actions/setup-java@v4
  with:
    distribution: temurin
    java-version: '17'

- uses: gradle/actions/setup-gradle@v3
  with:
    gradle-version: '8.2.1'

- name: Generate Gradle Wrapper (если его нет в репо)
  run: |
    if [ ! -f gradlew ]; then
      gradle wrapper --gradle-version 8.2.1
    fi
    chmod +x gradlew

- name: Build
  run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
